services:
  redis:
    image: redis:alpine
    restart: always
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    restart: always
    command: >
     sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn uploader.wsgi:application --bind 0.0.0.0:8000"
    container_name: django_project
    build: ./src
    volumes:
      - ./src/:/code/
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  worker:
    restart: always
    build:
      context: ./src/
    volumes:
      - ./src/:/code/
    command: celery -A uploader worker --loglevel=info
    depends_on:
      - redis
      - web
      - db
    env_file:
      - .env
